const { Configuration, OpenAIApi } = require('openai');
const stringSimilarity = require('string-similarity');
const cors = require('cors');
require('dotenv').config();

const configuration = new Configuration({
    apiKey: process.env.API_KEY,
});

const openAI = new OpenAIApi(configuration);

const handler = async (event, context) => {
    if (event.httpMethod !== 'POST') {
        return { statusCode: 405, body: 'Method Not Allowed' };
    }

    const reqBody = JSON.parse(event.body);
    const { question, answer } = reqBody;
    let message = ''
    try {
        const completion = await openAI.createChatCompletion({
            model: 'gpt-3.5-turbo',
            messages: [{ role: 'user', content: question }],
        });

        let points = 0;
        const similarity = stringSimilarity.compareTwoStrings(answer, completion.data.choices[0].message.content);
        if (similarity > points) {
            points = similarity;
        }

        // determine the correct response to give depending on the similarity level
        if (points > 0.7 && points <= 1.0) {
            message = 'According to the question you asked, the similarities between the answer provided by the student suggest a high level of similarity (80-100%). It is highly likely that the answer was generated by ChatGPT.';
        }

        else if (points >= 0.6 && points <= 0.69) {
            message = 'According to the question you asked, the similarities between the answer provided by the student suggest a moderate level of similarity (60-79%). It is possible that the answer was generated by ChatGPT.'
        }
        else if (points >= 0.4 && points <= 0.59) {
            message = 'According to the question you asked, the similarities between the answer provided by the student suggest a low level of similarity (40-59%). It is unlikely that the answer was generated by ChatGPT.';
        }
        else if (points >= 0.3 && points <= 0.39) {
            message = 'According to the question you asked, the similarities between the answer provided by the student suggest a very low level of similarity (30-39%). It is highly unlikely that the answer was generated by ChatGPT.';
        }
        else if (points >= 0.0 && points <= 0.29) {
            message = 'According to the question you asked, the similarities between the answer provided by the student suggest very little to no similarity (0-29%). It is extremely unlikely that the answer was generated by ChatGPT.';
        }

        return {
            statusCode: 200,
            body: JSON.stringify({ message: message, similarity: points }),
        };
    } catch (err) {
        return { statusCode: 400, body: JSON.stringify({ message: err }) };
    }
};

exports.handler = handler;
